---
#general bigip onboarding for f5-rs, hardening, templates and default profiels.

- name: Wait until BIG-IP is ready to make changes
  bigip_command: 
    commands: "run /util bash -c 'cat /var/prompt/ps1'"
  delegate_to: localhost
  delay: 30
  register: result
  retries: 60
  until: (result.stdout.find("Active") != -1 or result.stdout.find("Standby") != -1 or result.stdout.find("Unlicensed") != -1)
  ignore_errors: yes
  

- name: Configures hostname
  bigip_command: 
    commands: "modify /sys global-settings hostname {{ service_name }}-{{ branch }}-{{ aws_region}}-bigip.com"
  delegate_to: localhost

  
- name: change advisory text
  bigip_command: 
    commands: "modify sys db ui.advisory.text { value {{ service_name }}-{{ branch }}-{{ aws_region}}-bigip.com }"
  delegate_to: localhost

- name: change advisory status
  bigip_command: 
    commands: modify sys db ui.advisory.enabled { value "true" }
  delegate_to: localhost

- name: Configures advisory color
  bigip_command: 
    commands: modify sys db ui.advisory.color { value orange }
  delegate_to: localhost
  when: branch == "dev"  


- name: install websafe license id 
  bigip_command: 
    commands: "modify sys db license.antifraud.id value {{ vault_websafe_license_id }}"
  delegate_to: localhost
  ignore_errors: yes
  when: '"awaf" in onboard_services'
  
- name: install websafe license applicationencryption 
  bigip_command: 
    commands: "modify sys db license.antifraud.applicationencryption value {{ vault_websafe_license_application_encryption }}"
  delegate_to: localhost
  ignore_errors: yes
  when: '"awaf" in onboard_services'
    
- name: Install iApp Template for Virtual Service Insertion
  bigip_iapp_template:
    state: "{{ state }}"
    content: "{{ lookup('file', 'appsvcs_v2.0.004' + '.tmpl') }}"
    force: yes
  delegate_to: localhost
  
  
- name: Install iApp Template for Service Discovery of Pool Members
  delegate_to: localhost
  bigip_iapp_template:
    state: "{{ state }}"
    content: "{{ lookup('file', sd_iApp_template_name + '.tmpl') }}"
    force: yes
    partition: "{{partition}}"
  when: '"aws" in onboard_cloud'
  
- name: Install analytics iapp template 
  delegate_to: localhost
  bigip_iapp_template:
    state: "{{ state }}"
    content: "{{ lookup('file', 'f5.analytics.v3.7.1rc4' + '.tmpl') }}"
    force: yes
    partition: "{{partition}}"

- name: Deploy analytics service 
  delegate_to: localhost
  bigip_iapp_service:
      state: "{{ state }}"
      partition: "{{partition}}"
      name: "analytics-splunk"
      template: "/Common/f5.analytics.v3.7.1rc4"
      parameters: "{{ lookup('template', 'analytics.json') }}"
      strict_updates: "{{ strict_updates }}"
  register: result


#######################getting bigip auth token############################

- name: Getting bigip authentication token
  delegate_to: localhost
  uri:
    body: '{"username":"{{vault_bigip_rest_user}}","password":"{{vault_bigip_rest_password}}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{ bigip_ip_addr }}:{{ bigip_mgmt_port }}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: no
  register: bigip_auth_response
  
- name: assinging auth token to a variable 
  set_fact:
    bigip_auth_token: "{{ bigip_auth_response.json.token.token }}"

- name: Deploying updating ASM Logging Profile to send to Remote Analytics Server
  delegate_to: localhost
  uri:
    body: "{{ lookup('template', 'asm_logging_profile_payload.j2') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip_auth_token }}"
    method: POST
    status_code: 200, 201, 409
    url: "https://{{ bigip_ip_addr }}:{{ bigip_mgmt_port }}/mgmt/tm/security/log/profile"
    validate_certs: no
  

- name: Deploying updating ASM Logging ALL Profile
  delegate_to: localhost
  uri:
    body: "{{ lookup('template', 'asm_logging_profile_all_payload.j2') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip_auth_token }}"
    method: POST
    status_code: 200, 201, 409
    url: "https://{{ bigip_ip_addr }}:{{ bigip_mgmt_port }}/mgmt/tm/security/log/profile"
    validate_certs: no
  when: '"awaf" in onboard_services'

- name: Deploying updating AVR profile
  delegate_to: localhost
  uri:
    body: "{{ lookup('template', 'avr_profile_payload.j2') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip_auth_token }}"
    method: POST
    status_code: 200, 201, 409
    url: "https://{{ bigip_ip_addr }}:{{ bigip_mgmt_port }}/mgmt/tm/ltm/profile/analytics"
    validate_certs: no

- name: Deploying updating HTTP profile
  delegate_to: localhost
  uri:
    body: "{{ lookup('template', 'rs_http_profile_payload.j2') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip_auth_token }}"
    method: POST
    status_code: 200, 201, 409
    url: "https://{{ bigip_ip_addr }}:{{ bigip_mgmt_port }}/mgmt/tm/ltm/profile/http"
    validate_certs: no
    
- name: creating DNS resolver
  delegate_to: localhost
  uri:
    body: "{{ lookup('template', 'dns_resolver.j2') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip_auth_token }}"
    method: POST
    status_code: 200, 201, 409
    url: "https://{{ bigip_ip_addr }}:{{ bigip_mgmt_port }}/mgmt/tm/net/dns-resolver"
    validate_certs: no
    
    
############installing AS3#############################

- name: get rpm lenth
  shell: "wc -c {{ role_path }}/files/{{ as3_rpm }} | cut -f 1 -d ' '"
  register: as3_rpm_len_output
  
- name: put rpm len in a variable
  set_fact: 
    as3_rpm_len: "{{ as3_rpm_len_output.stdout }}"

- name: enable iappLX
  bigip_command: 
    commands: "run /util bash -c 'touch /var/config/rest/iapps/enable'"
  delegate_to: localhost
  
- name: uploading AS3 package
  shell: "curl -kv https://{{ bigip_ip_addr }}:{{ bigip_mgmt_port }}/mgmt/shared/file-transfer/uploads/{{ as3_rpm }} -H 'Content-Type: application/octet-stream' -H 'Content-Range: 0-{{ as3_rpm_len | int -1 }}/{{ as3_rpm_len}}' -H 'Content-Length: {{ as3_rpm_len}}' -H 'Connection: keep-alive' -H 'X-F5-Auth-Token: {{ bigip_auth_token }}' --data-binary @{{ role_path }}/files/{{ as3_rpm }}"
  register: installation
  
- name: set as3 install command
  set_fact: 
    as3_install_cmd: "'{'operation':'INSTALL','packageFilePath':'/var/config/rest/downloads/{{ as3_rpm }}'}'"

- name: installing as3 package
  delegate_to: localhost
  uri:
    body: "{{ lookup('template', 'as3_install_cmd.json') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip_auth_token }}"
      Origin: "https://{{ bigip_ip_addr }}:{{ bigip_mgmt_port }}"
    method: POST
    status_code: 202, 200, 409
    url: "https://{{ bigip_ip_addr }}:{{ bigip_mgmt_port }}/mgmt/shared/iapp/package-management-tasks"
    validate_certs: no

############################## saving bigip config####################   
    
- name: Saving the bigip config
  delegate_to: localhost
  uri:
    body: '{"command":"save"}'
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip_auth_token }}"
    method: POST
    status_code: 200, 201, 409
    url: "https://{{ bigip_ip_addr }}:{{ bigip_mgmt_port }}/mgmt/tm/sys/config"
    validate_certs: no
